{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 # What flags to pass to sudo\
# WARNING: leaving out the defaults might create unexpected behaviours\
#sudo_flags = -H -S -n\
\
# SSH timeout\
#timeout = 10\
\
# default user to use for playbooks if user is not specified\
# (/usr/bin/ansible will use current user as default)\
remote_user = sysadmin\
\
# logging is off by default unless this path is defined\
# if so defined, consider logrotate\
#log_path = /var/log/ansible.log\
\
# default module name for /usr/bin/ansible\
#module_name = command\
}